// <auto-generated />
namespace TeknolojiKovaniWebApi.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class deviceValue_added_firedalarmId : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(deviceValue_added_firedalarmId));
        
        string IMigrationMetadata.Id
        {
            get { return "201704282016586_deviceValue_added_firedalarmId"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
